# Use new trusty images, should yield newer compilers and packages
sudo: false
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++
    - compiler: gcc 7.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER=g++-7
    - compiler: clang
      env: COMPILER=clang++
    - compiler: clang 5.0
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env: COMPILER=clang++-5.0

packages:
  - libopencv-dev
script:
  - $COMPILER --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make -j$(nproc --all)
  - ./dkm_tests
  - ./dkm_bench
  