# Use new trusty images, should yield newer compilers and packages
sudo: false
dist: trusty
language: cpp

matrix:
  include:
    - compiler: g++-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - libopencv-dev
      env: COMPILER=g++-4.9
    - compiler: g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - libopencv-dev
      env: COMPILER=g++-7
    - compiler: clang++-3.4
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.4
          packages:
            - clang-3.4
            - clang++-3.4
            - libopencv-dev
      env: COMPILER=clang++-3.4
    - compiler: clang++-5.0
      addons:
        apt:
          packages:
            - libopencv-dev
      env: COMPILER=clang++
script:
  - $CXX --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make -j$(nproc --all)
  - ./dkm_tests
  - ./dkm_bench
  