# Use new trusty images, should yield newer compilers and packages
sudo: false
dist: trusty
language: cpp

matrix:
  include:
    - compiler: g++
    - compiler: g++-7
    - compiler: clang++-3.4
    - compiler: clang++

packages:
  - libopencv-dev
script:
  - $CXX --version
  - ls /usr/share/OpenCV
  - ls /usr/lib | grep -i opencv
  - mkdir build
  - cd build
  - cmake .. && make -j$(nproc --all)
  - ./dkm_tests
  - ./dkm_bench
  