language: cpp
compiler:
  - clang
  - gcc
install:
  - sudo apt-get update
  - sudo apt-get install -y libopencv-dev
script:
  - mkdir build
  - cd build
  - cmake .. && make
  - ./dkm_tests
  - ./dkm_bench
  