# Use new trusty images, should yield newer compilers and packages
sudo: false
dist: trusty
language: cpp

matrix:
  include:
    - compiler: g++-4.9
    - compiler: g++-7
    - compiler: clang++-3.4
    - compiler: clang++-5.0

packages:
  - libopencv-dev
script:
  - $CXX --version
  - mkdir build
  - cd build
  - cmake .. && make -j$(nproc --all)
  - ./dkm_tests
  - ./dkm_bench
  