# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
	- clang-3.6

language: cpp
compiler:
  - clang
  - gcc
install:
  - sudo apt-get update
  - sudo apt-get install -y libopencv-dev
script:
  - mkdir build
  - cd build
  - cmake .. && make
  - ./dkm_tests
  - ./dkm_bench
  